version: '3.8'

services:
  blog:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (optional if named Dockerfile)
    container_name: blog
    restart: always
    ports:
      - "8000:8000"  # Change the port as needed
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
    depends_on:
      - db
    volumes:
      - /Users/kirillstarkov/WORK/demo/Django_blog-1:/app

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpassword
    ports:
      - "5432:5432"  # Exposing PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: